# decide software version
export INSTALLED_PYTHON_VERSION="3.11"
export INSTALLED_CUDA_VERSION="12.4"
export INSTALLED_CUDA_ABBREV="cu124"
export INSTALLED_GCC_VERSION="11.2.0"
export INSTALLED_PYTORCH_VERSION="2.5.1"
export INSTALLED_TORCHVISION_VERSION="0.20.1"
export INSTALLED_TORCHAUDIO_VERSION="2.5.1"
